### ISSUE TITLE
Error: Unrecognised option '--id'

### ISSUE THREAD

**Issue by teaforthecat** [theforeman/hammer-cli-foreman-tasks#22]
Am I missing something? I'm trying to execute the command in the README.md. I have  a uuid, but when I run the below command I see the given output.

``` bash
$ hammer task progress --id 04a16b07-2b01-4a51-8e45-ca7c9437b8e1
Error: Unrecognised option '--id'

See: 'hammer task progress --help'
```

**Comment by mmoll** [comment]
/cc @adamruzicka @iNecas
This works fine for me with 0.0.12, I guess this can get closed.

**Comment by iNecas** [comment]
Yes, I'm pretty sure this has been resolved in the past 3 years.
